version: "3.8"

services:
  postgres:
    image: postgres:13.4-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - volume_postgres:/var/lib/postgresql/data

volumes:
  volume_postgres:
